### ISSUE TITLE
ValueError: need at least one array to concatenate

### ISSUE THREAD

**Issue by GuptaVishu2002** [CompRhys/roost#2]
I am trying to use a database created out of OQMD to test the accuracy of the roost bu it is showing the following error:

```
Traceback (most recent call last):
  File "train.py", line 435, in <module>
    main()
  File "train.py", line 115, in main
    ensemble(args.data_id, args.ensemble, train_set, test_set,)
  File "train.py", line 177, in ensemble
    _, sample_target, _, _ = collate_batch(train_subset)
  File "/home/roost/roost/data.py", line 296, in collate_batch
    target, comp, cry_id) in enumerate(dataset_list):
  File "/home/.local/lib/python3.6/site-packages/torch/utils/data/dataset.py", line 257, in __getitem__
    return self.dataset[self.indices[idx]]
  File "/home/roost/roost/data.py", line 227, in __getitem__
    for element in elements])
  File "/home/.local/lib/python3.6/site-packages/numpy/core/shape_base.py", line 283, in vstack
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
ValueError: need at least one array to concatenate
```

The dataset that I am trying to use to test roost can be downloaded from the following link:
https://1drv.ms/u/s!AnHk4LRXBfPOlzBd01vfb89jBtjC?e=IwdTvr

Can you tell me what is wrong with the dataset that I am trying to use?

**Comment by CompRhys** [comment]
@GuptaVishu2002 it appears as if the error comes when you're collecting the features for the list of elements. The link you sent doesn't load for me but I would guess that either: you have compositions that are either all lowercase or all uppercase in which case the parsing script I wrote won't work or you have an empty row in the input file. Maybe the quickest way to debug this would be to edit line 228 in roost/data.py and change 'AssertionError' to 'ValueError', rerunning train.py rather than crashing it will now print the composition and exit. If you post which composition is causing it to crash then we might be able to understand what is going wrong.

**Comment by GuptaVishu2002** [comment]
After changing  'AssertionError' to 'ValueError' and rerunning train.py, the program didn't gave any output and it just stopped running. So I was not able to get any composition which might be causing the problem. Also, the compositions are not all lowercase or all uppercase, so that may not be the reason for the error here. I have uploaded the zip file of the data set that I am using to conduct the experiment. It would be grateful if you can help me with the debug of the data set because I am not able to figure out what exactly is causing the problem.
[oqmd_roost.zip](https://github.com/CompRhys/roost/files/4538799/oqmd_roost.zip)

**Comment by CompRhys** [comment]
@GuptaVishu2002 `241200,,1.13603978815242` This row in your data set is the issue, let me know if you have anymore problems with running the code!

**Comment by CompRhys** [comment]
@GuptaVishu2002 did you get a result for this in the end? I would be interested to know how it compares assuming it's the same `ElemNet` dataset as in the nat comm paper.

**Comment by GuptaVishu2002** [comment]
I used a newer OQMD dataset, which I downloaded on 2020/01/18. With matscholar-embedding, it is showing better performance as compared to the model presented in nat comm paper. I am trying to understand Roost architecture but am not familiar with GNN. If possible could you explain how the embedding part is working?

**Comment by CompRhys** [comment]
The key idea is that `Roost` operates on the embeddings of elements within a material rather than an embedding of the material.  

In `ElemNet` a one-hot encoding multiplied by the atomic fractions provides an embedding of the material that is used as the input, an alternative might be to use the `magpie` descriptor set.  

Here we do the same but from atom types, we can use a one-hot encoding (and for large data sets it makes no difference) or we can use a more physical embedding such as `matscholar` that tries to capture some physics (you can view as being analogous to the difference between the `ElemNet` input and `magpie`).

Although I draw analogy to MPNNs/GNNs it's only illustrative and learning more about them won't necessarily make the model make much more sense. The "dense weighted graph" idea I use to visualise the problem is not a traditional graph type that these models are used for.

**Comment by GuptaVishu2002** [comment]
Correct me if I am wrong but, if I were to summarize what you just explained, you are using matscholar embedding for each of the element which is multiplied by the atomic fraction as an input to the dense weighted graph which is a form of GNN, right?
Also, can you tell what kind of properties is elem-embedding taking into account?

**Comment by CompRhys** [comment]
We don't multiply the element embeddings by the atomic fraction we bring in the atomic fractions via the weighted attention operation. 

`magpie`-esque fayre - Z, mass, radii, electronegativities of various flavours. I used a bigger feature set and interpolated the gaps

**Comment by GuptaVishu2002** [comment]
Thank you so much for the clarification. I really appreciate your work and the new ideas that you have incorporated. Would you mind if I ask you something regarding `roost ` in the near future?

**Comment by GuptaVishu2002** [comment]
I see that you are giving `Simple Network` to the `WeightedAttention` and performing `scatter_max` and` scatter add` on the `Simple Network`. How does this thing work?

**Comment by CompRhys** [comment]
In a material aAbBcC where capitals are atom types and lower case are fractional weights. At any given point in the network A, B and C all have some embedded vector that 'describes' them. When we do the message passing we concatenate the different pairs of these embeddings, so in this material we would have the following pairings AB, AC, BA, BC, CA, CB. The `WeightedAttention` has two parts; one that learns a scalar [ g(...) ] and another that learns a 'perturbation' [ f(...) ] the same size as the element embeddings. The scalar 'learns' how important a pair is and then the perturbation is used to update the embedding accordingly. In this toy case we have A' = A + (g(b, AB)f(AB)+ g(c, AC)f(AC))/(g(b, AB) + g(c, AC)). The `scatter` operations in the code are used to pick out the correct pairings based on lists of lists.

**Comment by GuptaVishu2002** [comment]
Thanks for the clarification. 
Also, the reason residual network has 2 output is because you are finding the result of 2 metrics MAE and RMSE or is it something else?
