### ISSUE TITLE
Error when setting validation size.

### ISSUE THREAD

**Issue by K1423** [CompRhys/roost#4]
`(base) C:\Users\PARKDONGSU\Desktop\roost-master>python train.py --data-path C:\Users\PARKDONGSU\Desktop\roost-master\data\datasets\my_data_mp.csv  --optim Adam --lr 5e-4 --bsize 1500 --epoch 500 --val-size 0.1 --test-size 0.1 --run-id 001
The model will run on the cuda device
using 0.1 of training set as test set
using 0.1 of training set as validation set
Traceback (most recent call last):
  File "train.py", line 442, in <module>
    main()
  File "train.py", line 114, in main
    ensemble(args.data_id, args.ensemble, train_set, test_set,)
  File "train.py", line 181, in ensemble
    model, normalizer = init_model(train_set.dataset)
  File "train.py", line 29, in init_model
    model = Roost(dataset.atom_fea_dim,
AttributeError: 'Subset' object has no attribute 'atom_fea_dim'`

I got errors when setting validation size.
It runs well just with test size only.

**Comment by CompRhys** [comment]
I think the changes I just pushed should fix this. I did a recent rewrite to streamline passing the embedding size argument into `init_model()` but this didn't play nicely with nested subsets which is what led to the problem here and I didn't catch it as I've recently been using `val_path` not `val_size`.
